In [2]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\users\91969\anaconda\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\91969\anaconda\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\91969\anaconda\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)
Requirement already satisfied: requests in c:\users\91969\anaconda\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\91969\anaconda\lib\site-packages (from requests) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91969\anaconda\lib\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91969\anaconda\lib\site-packages (from requests) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\91969\anaconda\lib\site-packages (from requests) (2.0.4)

In [2]:
from bs4 import BeautifulSoup
import requests

Question no 1

In [36]:
page = requests.get("https://wikipedia.org")
page

In [37]:
soup = BeautifulSoup(page.content)

In [38]:
header = []
for i in soup.find_all('h1', class_="central-textlogo-wrapper"):
    header.append(i.text)

In [23]:
header

['\n\nWikipedia\n\nThe Free Encyclopedia\n']

Question no 2

In [26]:
imdb = requests.get("https://www.imdb.com/list/ls055386972/?sort=user_rating,desc&st_dt=&mode=detail&page=1")
imdb

In [27]:
soup1 = BeautifulSoup(imdb.content)

In [34]:
name = []
for i in soup1.find_all('h3', class_="lister-item-header"):
    name.append(i.text)

In [37]:
name

['\n1.\nThe Shawshank Redemption\n(1994)\n',
 '\n2.\nThe Godfather\n(1972)\n',
 '\n3.\nThe Dark Knight\n(2008)\n',
 "\n4.\nSchindler's List\n(1993)\n",
 '\n5.\n12 Angry Men\n(1957)\n',
 '\n6.\nIl buono, il brutto, il cattivo\n(1966)\n',
 '\n7.\nSaving Private Ryan\n(1998)\n',
 '\n8.\nThe Green Mile\n(1999)\n',
 '\n9.\nTerminator 2: Judgment Day\n(1991)\n',
 '\n10.\nLa vita è bella\n(1997)\n',
 '\n11.\nShichinin no samurai\n(1954)\n',
 "\n12.\nIt's a Wonderful Life\n(1946)\n",
 '\n13.\nGladiator\n(2000)\n',
 '\n14.\nLéon\n(1994)\n',
 '\n15.\nAlien\n(1979)\n',
 '\n16.\nBack to the Future\n(1985)\n',
 '\n17.\nThe Pianist\n(2002)\n',
 '\n18.\nThe Intouchables\n(2011)\n',
 '\n19.\nThe Shining\n(1980)\n',
 '\n20.\nBraveheart\n(1995)\n',
 '\n21.\nRequiem for a Dream\n(2000)\n',
 '\n22.\nJodaeiye Nader az Simin\n(2011)\n',
 '\n23.\nJurassic Park\n(1993)\n',
 '\n24.\nThe Sixth Sense\n(1999)\n',
 '\n25.\nKill Bill: Vol. 1\n(2003)\n',
 '\n26.\nFinding Nemo\n(2003)\n',
 '\n27.\nA Beautiful Mind\n(2001)\n',
 '\n28.\nEl secreto de sus ojos\n(2009)\n',
 '\n29.\nThe Bridge on the River Kwai\n(1957)\n',
 '\n30.\nBacheha-Ye aseman\n(1997)\n',
 '\n31.\nThe Exorcist\n(1973)\n',
 '\n32.\nSalinui chueok\n(2003)\n',
 '\n33.\nBen-Hur\n(1959)\n',
 '\n34.\nGran Torino\n(2008)\n',
 "\n35.\nHachi: A Dog's Tale\n(2009)\n",
 '\n36.\nAmores perros\n(2000)\n',
 '\n37.\nNae meorisokui jiwoogae\n(2004)\n',
 '\n38.\nThe Pursuit of Happyness\n(2006)\n',
 '\n39.\nYeopgijeogin geunyeo\n(2001)\n',
 '\n40.\nBom yeoreum gaeul gyeoul geurigo bom\n(2003)\n',
 '\n41.\nOkuribito\n(2008)\n',
 '\n42.\nCentral do Brasil\n(1998)\n',
 '\n43.\nTitanic\n(1997)\n',
 '\n44.\nBin-jip\n(2004)\n',
 '\n45.\nVozvrashchenie\n(2003)\n',
 '\n46.\nCast Away\n(2000)\n',
 '\n47.\nApocalypto\n(2006)\n',
 '\n48.\nTaken\n(I) (2008)\n',
 '\n49.\nAng-ma-reul bo-at-da\n(2010)\n',
 '\n50.\nWo de fu qin mu qin\n(1999)\n']

In [40]:
release = []
for i in soup1.find_all('span', class_="lister-item-year text-muted unbold"):
    release.append(i.text)

In [41]:
release

['(1994)',
 '(1972)',
 '(2008)',
 '(1993)',
 '(1957)',
 '(1966)',
 '(1998)',
 '(1999)',
 '(1991)',
 '(1997)',
 '(1954)',
 '(1946)',
 '(2000)',
 '(1994)',
 '(1979)',
 '(1985)',
 '(2002)',
 '(2011)',
 '(1980)',
 '(1995)',
 '(2000)',
 '(2011)',
 '(1993)',
 '(1999)',
 '(2003)',
 '(2003)',
 '(2001)',
 '(2009)',
 '(1957)',
 '(1997)',
 '(1973)',
 '(2003)',
 '(1959)',
 '(2008)',
 '(2009)',
 '(2000)',
 '(2004)',
 '(2006)',
 '(2001)',
 '(2003)',
 '(2008)',
 '(1998)',
 '(1997)',
 '(2004)',
 '(2003)',
 '(2000)',
 '(2006)',
 '(I) (2008)',
 '(2010)',
 '(1999)']

In [46]:
rating = []
for i in soup1.find_all('span',class_="ipl-rating-star__rating"):
    rating.append(i.text)
    
    
rating

['9.3',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.6',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.5',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.4',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.4',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.3',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.3',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.2',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8.1',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '8',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '7.9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 '5',
 'Rate',
 '6',
 'Rate',
 '7',
 'Rate',
 '8',
 'Rate',
 '9',
 'Rate',
 '10',
 'Rate',
 '7.9',
 '0',
 'Rate',
 '1',
 'Rate',
 '2',
 'Rate',
 '3',
 'Rate',
 '4',
 'Rate',
 ...]

Question no 9

In [47]:
rest = requests.get('https://www.dineout.co.in/delhi-restaurants/welcome-back')
rest

In [48]:
soup2 = BeautifulSoup(rest.content)

In [49]:
restname = []
for i in soup2.find_all('a', class_="restnt-name ellipsis"):
    restname.append(i.text)

In [50]:
restname

['Tamasha',
 'Local',
 'Ministry Of Beer',
 'Openhouse Cafe',
 'Unplugged Courtyard',
 'Station Bar',
 'The Junkyard Cafe',
 'Chido',
 "Berco's",
 'The G.T. Road',
 'QBA',
 '38 Barracks',
 'Out Of The Box Courtyard',
 'Farzi Cafe',
 'Ardor 2.1 Restaurant and Lounge',
 'Cafe Delhi Heights',
 'My Bar Headquarters',
 'Sandoz',
 'Wok in the Clouds',
 'Connaught Club House',
 'Gola Sizzlers']

In [60]:
cuisine = []
for i in soup2.find_all('span',class_="double-line-ellipsis"):
    cuisine.append(i.text.split('|')[1])

In [61]:
cuisine

[' Continental, Asian, Italian, North Indian',
 ' North Indian, Asian, Continental',
 ' North Indian, Continental, American, Asian',
 ' North Indian, Asian, Italian',
 ' North Indian, Italian, Chinese, Turkish, Continental',
 ' Italian, Chinese, North Indian, Fast Food',
 ' North Indian, Continental, Chinese, Fast Food',
 ' North Indian, Italian, Continental, Asian, Finger Food',
 ' Chinese, Thai',
 ' North Indian',
 ' North Indian, Continental, Italian',
 ' North Indian, Chinese, Continental',
 ' North Indian, Mediterranean, Chinese, Italian',
 ' Modern Indian, Continental, Finger Food',
 ' North Indian, Chinese, Italian, Continental',
 ' Continental, North Indian, Beverages, Chinese, Italian',
 ' North Indian, Chinese',
 ' North Indian, Continental',
 ' Chinese, Thai, Continental, North Indian, Asian',
 ' North Indian, Continental, Asian, Chinese',
 ' Chinese, North Indian, Italian']

In [64]:
location = []
for i in soup2.find_all('div', class_="restnt-loc ellipsis"):
    location.append(i.text)

In [65]:
location

['Connaught Place, Central Delhi',
 'Scindia House,Connaught Place, Central Delhi',
 'M-Block,Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'F-Block,Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'M-Block,Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'M-Block,Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Janpath, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi',
 'Connaught Place, Central Delhi']

In [66]:
ratings = []
for i in soup2.find_all('div', class_="restnt-rating rating-4"):
    ratings.append(i.text)

In [67]:
ratings

['4.2',
 '4',
 '4',
 '4.1',
 '4',
 '4',
 '4.1',
 '4.2',
 '4.3',
 '4.3',
 '4.2',
 '4.3',
 '4.1',
 '4.1',
 '4.1',
 '4.3',
 '4',
 '4',
 '4.3',
 '4.2',
 '4.2']

In [68]:
images = []
for i in soup2.find_all('img', class_="no-img"):
    images.append(i.get('data-src'))

In [69]:
images

['https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/a/j/p20996-145631488756cd9a0796608.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/b/t/p27452-15020105505986dcb6d147f.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/a/d/p32381-1495943585592a49a166fe7.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/j/y/p19748-16474299906231c96621c58.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/u/y/p20941-15700828565d959028e9f28.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/9/i/b/p971-165909823762e3d47db6d56.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/s/y/p20298-1664186585633178d99f1db.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/9/r/n/p97184-167462459063d0be4e75dd6.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/t/u/p237-16468990666229af7a72b08.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/m/u/p31393-15972091555f337a43bb961.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/e/e/p29906-16183962346076c44ac433d.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/y/j/p21171-166019927162f4a167b10af.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/x/t/p83921-16017104805f782990b9b0c.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/y/y/p4199-164188203361dd21b1a3174.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/y/m/p221-16455303976214cd1d7a086.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/m/h/p35926-15233509655acc7db5718fb.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/d/f/p19636-16463919576221f295ae1f1.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/e/u/p80493-16064603115fc0a397716de.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/f/s/p2669-1499666296596317787f36d.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/c/z/p77626-15833232035e5f98437554f.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/u/n/p2617-1617631577606b19598001e.jpg?tr=tr:n-medium']

In [32]:
import pandas as pd

In [71]:
print(len(restname),len(cuisine),len(location),len(ratings),len(images))

21 21 21 21 21

In [73]:
DF = pd.DataFrame({'Restaurant Name': restname,'Cuisine': cuisine,'Location':location,'Ratings':ratings,'Images URL':images})
DF

,Restaurant Name,Cuisine,Location,Ratings,Images URL
0,Tamasha,"Continental, Asian, Italian, North Indian","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
1,Local,"North Indian, Asian, Continental","Scindia House,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
2,Ministry Of Beer,"North Indian, Continental, American, Asian","M-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
3,Openhouse Cafe,"North Indian, Asian, Italian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
4,Unplugged Courtyard,"North Indian, Italian, Chinese, Turkish, Cont...","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
5,Station Bar,"Italian, Chinese, North Indian, Fast Food","F-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
6,The Junkyard Cafe,"North Indian, Continental, Chinese, Fast Food","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
7,Chido,"North Indian, Italian, Continental, Asian, Fi...","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
8,Berco's,"Chinese, Thai","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
9,The G.T. Road,North Indian,"M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
10,QBA,"North Indian, Continental, Italian","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
11,38 Barracks,"North Indian, Chinese, Continental","M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
12,Out Of The Box Courtyard,"North Indian, Mediterranean, Chinese, Italian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
13,Farzi Cafe,"Modern Indian, Continental, Finger Food","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
14,Ardor 2.1 Restaurant and Lounge,"North Indian, Chinese, Italian, Continental","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
15,Cafe Delhi Heights,"Continental, North Indian, Beverages, Chinese...","Janpath, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
16,My Bar Headquarters,"North Indian, Chinese","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
17,Sandoz,"North Indian, Continental","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
18,Wok in the Clouds,"Chinese, Thai, Continental, North Indian, Asian","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
19,Connaught Club House,"North Indian, Continental, Asian, Chinese","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
20,Gola Sizzlers,"Chinese, North Indian, Italian","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...

Question no 4

In [74]:
former = requests.get('https://presidentofindia.nic.in/former-presidents.htm')
former

In [75]:
pres = BeautifulSoup(former.content)

In [79]:
name = []
for i in pres.find_all('div', class_="presidentListing"):
    name.append(i.text)
    
name

['\nShri Ram Nath Kovind (birth - 1945)\nTerm of Office: 25 July, 2017 to 25 July, 2022 \nhttps://ramnathkovind.nic.in\n',
 '\nShri Pranab Mukherjee (1935-2020)\nTerm of Office: 25 July, 2012 to 25 July, 2017 \nhttp://pranabmukherjee.nic.in\n',
 '\nSmt Pratibha Devisingh Patil (birth - 1934)\nTerm of Office: 25 July, 2007 to 25 July, 2012 \nhttp://pratibhapatil.nic.in\n',
 '\nDR. A.P.J. Abdul Kalam (1931-2015)\nTerm of Office: 25 July, 2002 to 25 July, 2007 \nhttp://abdulkalam.nic.in\n',
 '\nShri K. R. Narayanan (1920 - 2005)\nTerm of Office: 25 July, 1997 to 25 July, 2002 \n',
 '\nDr Shankar Dayal Sharma (1918-1999)\nTerm of Office: 25 July, 1992 to 25 July, 1997 \n',
 '\nShri R Venkataraman (1910-2009)\nTerm of Office: 25 July, 1987 to 25 July, 1992 \n',
 '\nGiani Zail Singh (1916-1994)\nTerm of Office: 25 July, 1982 to 25 July, 1987 \n',
 '\nShri Neelam Sanjiva Reddy (1913-1996)\nTerm of Office: 25 July, 1977 to 25 July, 1982 \n',
 '\nDr. Fakhruddin Ali Ahmed (1905-1977)\nTerm of Office: 24 August, 1974 to 11 February, 1977\n',
 '\nShri Varahagiri Venkata Giri (1894-1980)\nTerm of Office: 3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974\n',
 '\nDr. Zakir Husain (1897-1969)\nTerm of Office: 13 May, 1967 to 3 May, 1969\n',
 '\nDr. Sarvepalli Radhakrishnan (1888-1975)\nTerm of Office: 13 May, 1962 to 13 May, 1967\n',
 '\nDr. Rajendra Prasad (1884-1963) \nTerm of Office: 26 January, 1950 to 13 May, 1962\n']

In [82]:
DF = pd.DataFrame({'Name':name})
DF

                                                 Name
0   \nShri Ram Nath Kovind (birth - 1945)\nTerm of...
1   \nShri Pranab Mukherjee (1935-2020)\nTerm of O...
2   \nSmt Pratibha Devisingh Patil (birth - 1934)\...
3   \nDR. A.P.J. Abdul Kalam (1931-2015)\nTerm of ...
4   \nShri K. R. Narayanan (1920 - 2005)\nTerm of ...
5   \nDr Shankar Dayal Sharma (1918-1999)\nTerm of...
6   \nShri R Venkataraman (1910-2009)\nTerm of Off...
7   \nGiani Zail Singh (1916-1994)\nTerm of Office...
8   \nShri Neelam Sanjiva Reddy (1913-1996)\nTerm ...
9   \nDr. Fakhruddin Ali Ahmed (1905-1977)\nTerm o...
10  \nShri Varahagiri Venkata Giri (1894-1980)\nTe...
11  \nDr. Zakir Husain (1897-1969)\nTerm of Office...
12  \nDr. Sarvepalli Radhakrishnan (1888-1975)\nTe...
13  \nDr. Rajendra Prasad (1884-1963) \nTerm of Of...

Question no 7(i m unable to find class and tag of news link so preparing dataframe on the basis of headline and time

In [84]:
new = requests.get('https://www.cnbc.com/world/?region=world')
new

In [85]:
news = BeautifulSoup(new.content)

In [86]:
headline = []
for i in news.find_all('a', class_='LatestNews-headline'):
    headline.append(i.text)
headline

['These stocks could benefit from lower tax refunds, according to Stephens',
 'U.S. appeals decision striking down free Obamacare coverage of preventive care',
 'The top 10 states with the longest life expectancy and healthiest lifestyles',
 "This week's top S&P 500 stocks include First Republic and this casino owner",
 '‘Rust’ assistant director pleads guilty to gun charge in movie set shooting case',
 "Investors 'are pretty afraid,' financial psychologist says: These steps can help  ",
 'Bitcoin heads for its third positive up month, best quarter since 2021',
 'Paying more and earning less: How inflation disproportionately hurts women',
 'California to require half of all heavy trucks sales to be electric by 2035',
 'Tesla issues recall on Semi over defective brake module, rollaway risk',
 'Investor Dan Niles likes these tech stocks heading into the second quarter',
 'Vince McMahon locks in two-year contract as WWE looks for buyers ',
 'As the cost of living skyrockets, money is the only thing binding some couples',
 'April is usually the best month for the Dow. Here’s why it typically rallies',
 "6 steps to teach your kids how to say 'I'm sorry'",
 'Wall Street looks to finish Q1 higher as our tech stocks shine',
 'Stocks making the biggest moves midday: Bed Bath & Beyond, Nikola and more',
 "Carl Icahn blasts Illumina for CEO's pay bump despite drop in market value ",
 'Social Security trust funds depletion date moves a year earlier to 2034: report',
 'Biden Interior proposes leasing public lands for conservation',
 'Investors prefer dividend stocks as volatility persists, CNBC survey shows',
 'Harvard gut doctor: Avoid these 8 foods if you always feel bloated after eating—what to eat instead',
 'Why procrastinating on your IRA contributions could cost you thousands',
 'UBS sees a rally in these bank stocks ahead as bank crisis appears contained',
 'San Francisco Fed leader likely not a major player in SVB saga, officials say',
 'Sen. Elizabeth Warren says she wants to make banking boring again',
 '10 in-demand side hustles you can do from home—some can pay as much as $100/hour',
 "It's the U.S., not Europe's banking system that's a concern, top economists say",
 'Trump faces about 30 criminal counts for document fraud in New York indictment',
 'Investors believe the stock market is set for losses, CNBC survey shows']

In [87]:
print(len(headline))

30

In [88]:
time = []
for i in news.find_all('time',class_="LatestNews-timestamp"):
    time.append(i.text)
time

['12 Min Ago',
 '25 Min Ago',
 '27 Min Ago',
 '44 Min Ago',
 '46 Min Ago',
 '51 Min Ago',
 '57 Min Ago',
 '60 Min Ago',
 '1 Hour Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '2 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '4 Hours Ago',
 '4 Hours Ago',
 '4 Hours Ago',
 '4 Hours Ago',
 '5 Hours Ago',
 '5 Hours Ago',
 '5 Hours Ago']

In [89]:
print(len(time))

30

In [90]:
Df = pd.DataFrame({'Headline':headline,'Time':time})
Df

                                             Headline         Time
0   These stocks could benefit from lower tax refu...   12 Min Ago
1   U.S. appeals decision striking down free Obama...   25 Min Ago
2   The top 10 states with the longest life expect...   27 Min Ago
3   This week's top S&P 500 stocks include First R...   44 Min Ago
4   ‘Rust’ assistant director pleads guilty to gun...   46 Min Ago
5   Investors 'are pretty afraid,' financial psych...   51 Min Ago
6   Bitcoin heads for its third positive up month,...   57 Min Ago
7   Paying more and earning less: How inflation di...   60 Min Ago
8   California to require half of all heavy trucks...   1 Hour Ago
9   Tesla issues recall on Semi over defective bra...  2 Hours Ago
10  Investor Dan Niles likes these tech stocks hea...  2 Hours Ago
11  Vince McMahon locks in two-year contract as WW...  2 Hours Ago
12  As the cost of living skyrockets, money is the...  2 Hours Ago
13  April is usually the best month for the Dow. H...  2 Hours Ago
14  6 steps to teach your kids how to say 'I'm sorry'  2 Hours Ago
15  Wall Street looks to finish Q1 higher as our t...  2 Hours Ago
16  Stocks making the biggest moves midday: Bed Ba...  2 Hours Ago
17  Carl Icahn blasts Illumina for CEO's pay bump ...  2 Hours Ago
18  Social Security trust funds depletion date mov...  2 Hours Ago
19  Biden Interior proposes leasing public lands f...  3 Hours Ago
20  Investors prefer dividend stocks as volatility...  3 Hours Ago
21  Harvard gut doctor: Avoid these 8 foods if you...  3 Hours Ago
22  Why procrastinating on your IRA contributions ...  3 Hours Ago
23  UBS sees a rally in these bank stocks ahead as...  4 Hours Ago
24  San Francisco Fed leader likely not a major pl...  4 Hours Ago
25  Sen. Elizabeth Warren says she wants to make b...  4 Hours Ago
26  10 in-demand side hustles you can do from home...  4 Hours Ago
27  It's the U.S., not Europe's banking system tha...  5 Hours Ago
28  Trump faces about 30 criminal counts for docum...  5 Hours Ago
29  Investors believe the stock market is set for ...  5 Hours Ago

Question 5 -1

In [5]:
team = requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
team

In [6]:
soup3 = BeautifulSoup(team.content)

In [8]:
top10 = []
for i in soup3.find_all('span', class_="u-hide-phablet"):
    top10.append(i.text)
top10

['Australia',
 'India',
 'New Zealand',
 'England',
 'Pakistan',
 'South Africa',
 'Bangladesh',
 'Sri Lanka',
 'West Indies',
 'Afghanistan',
 'Ireland',
 'Scotland',
 'Zimbabwe',
 'Netherlands',
 'Nepal',
 'Oman',
 'Namibia',
 'United States',
 'UAE',
 'Papua New Guinea']

In [21]:
matches = []
for i in soup3.find_all('td', class_="rankings-block__banner--matches"):
    matches.append(i.text)
    
    
matches

['35']

same is happening for points and ratings thats why i m unable to make dataframe

In [22]:
##Question no 8

In [23]:
journal = requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
journal

In [25]:
AI = BeautifulSoup(journal.content)

In [26]:
heading = []
for i in AI.find_all('a', class_="sc-5smygv-0 fIXTHm"):
    heading.append(i.text)
heading

['Reward is enough',
 'Making sense of raw input',
 'Law and logic: A review from an argumentation perspective',
 'Creativity and artificial intelligence',
 'Artificial cognition for social human–robot interaction: An implementation',
 'Explanation in artificial intelligence: Insights from the social sciences',
 'Making sense of sensory input',
 'Conflict-based search for optimal multi-agent pathfinding',
 'Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning',
 'The Hanabi challenge: A new frontier for AI research',
 'Evaluating XAI: A comparison of rule-based and example-based explanations',
 'Argumentation in artificial intelligence',
 'Algorithms for computing strategies in two-player simultaneous move games',
 'Multiple object tracking: A literature review',
 'Selection of relevant features and examples in machine learning',
 'A survey of inverse reinforcement learning: Challenges, methods and progress',
 'Explaining individual predictions when features are dependent: More accurate approximations to Shapley values',
 'A review of possible effects of cognitive biases on interpretation of rule-based machine learning models',
 'Integrating social power into the decision-making of cognitive agents',
 "“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems",
 'Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies',
 'Algorithm runtime prediction: Methods & evaluation',
 'Wrappers for feature subset selection',
 'Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics',
 'Quantum computation, quantum theory and AI']

In [27]:
authors = []
for i in AI.find_all('span', class_="sc-1w3fpd7-0 dnCnAO"):
    authors.append(i.text)
authors

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [28]:
date =[]
for i in AI.find_all('span', class_="sc-1thf9ly-2 dvggWt"):
    date.append(i.text)
date

['October 2021',
 'October 2021',
 'October 2015',
 'August 1998',
 'June 2017',
 'February 2019',
 'April 2021',
 'February 2015',
 'August 1999',
 'March 2020',
 'February 2021',
 'October 2007',
 'August 2016',
 'April 2021',
 'December 1997',
 'August 2021',
 'September 2021',
 'June 2021',
 'December 2016',
 'September 2021',
 'May 2021',
 'January 2014',
 'December 1997',
 'October 2021',
 'February 2010']

In [30]:
#in url i m not able to find tag and class
url =[]
for i in AI.find_all('span', class_="sc-1w3fpd7-0 dnCnAO"):
    url.append(i.text)
url

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [33]:
DF = pd.DataFrame({'Paper Title':heading, 'Authors':authors,'Published Date':date})
DF

,Paper Title,Authors,Published Date
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010